### ISSUE TITLE
Create resources from serverless.yml in moto services

### ISSUE THREAD

**Issue by gertjvr** [gertjvr/serverless-plugin-simulate#1]
# Feature Proposal
## Description

TL;DR Emulate [CloudFormation](https://aws.amazon.com/cloudformation/)

The plugin should parse the resource section of `serverless.yml`, for any resources that [moto](https://github.com/spulec/moto) could emulate like [s3](https://aws.amazon.com/s3/) `bucket` or [sns](https://aws.amazon.com/sns/) `topic` and create them using the information provided. So that the `serverless-docker` plugin can _just run_ without the need for a `reset-the-world` script

Similar or dependent issues:
- None
## Additional Data
- None

**Comment by hassankhan** [comment]
What about resources that aren't specified in the CloudFormation instructions? Would there still be a way of simulating those?

**Comment by gertjvr** [comment]
Resolved with #37
