### ISSUE TITLE
Use Atlassian LocalStack?

### ISSUE THREAD

**Issue by hassankhan** [gertjvr/serverless-plugin-simulate#26]
# This is a Feature Proposal

## Description
Use Atlassian LocalStack: https://github.com/atlassian/localstack

They seem to have done the hard work of making a bunch of AWS services, the only one they don't yet support is Cognito. Rather than duplicating the work, perhaps its better to use what they have and make this plugin a thin shim over it?

**Comment by johncmckim** [comment]
That's an interesting project! It certainly does a lot of things we don't currently do, i.e. kinesis firehose, s3, sns ect.

Unfortunately, it also looks like they take the same approach as Serverless Offline when it comes to Lambda. They execute functions in process. As a result, they only support python. Local stack just brings three tools together [moto](https://github.com/spulec/moto), [kinesalie](https://github.com/mhart/kinesalite) and [dynalite](https://github.com/mhart/dynalite). 

We have another issue that looks at simulating more of AWS by using moto #1. It would be great to look at how we can add wider aws support via [moto](https://github.com/spulec/moto), [kinesalie](https://github.com/mhart/kinesalite) and [dynalite](https://github.com/mhart/dynalite).

**Comment by hassankhan** [comment]
Fair enough, personally I'd love to see something that adds DynamoDB and Cognito, as elsewhere mentioned in the project, `serverless-offline` is not great, but it's the only thing around at the moment.

I tried to have a look into writing a PR to allow for Cognito authorizers but I just can't find any documentation on how to talk to it directly (feel like I missed something), would love to try and help if possible 😄

**Comment by johncmckim** [comment]
DynamoDB + Cognito would be fantastic. Any help you can give us is very welcome.

For DynamoDB, we should look at [dynalite](https://github.com/mhart/dynalite) and [dynamodb local](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html). I'm leaning towards dynalite as it would be easy to integrate. I've added #28 so we can discuss.

In regards to Cognito. We have another issue open #2 for cognito. I'll go there to add some of my thoughts. 

I'm going to close this issue but let's discuss adding support in those other issues.
