### ISSUE TITLE
Investigate Simulating Kinesis

### ISSUE THREAD

**Issue by johncmckim** [gertjvr/serverless-plugin-simulate#29]
# This is a Feature Proposal

## Description
It may be possible to support kinesis locally with [kinesalite](https://github.com/mhart/kinesalite) and [kinesis](https://github.com/mhart/kinesis). This would require some more investigation.

It would be important to inject a `SERVERLESS_SIMULATE_KINESIS_ENDPOINT` environment variable into the container.

**Comment by gertjvr** [comment]
Resolved with #37
