### ISSUE TITLE
Payload cannot receive though lamda invoke call.

### ISSUE THREAD

**Issue by yoyeung** [gertjvr/serverless-plugin-simulate#44]
# This is a Bug Report

## Description

For bug reports:
call the example project by
```
curl http://localhost:5000/bff
```
and I try to print out the the event from bff.backend

```
const backend = (event, context, callback) => {
  // info.log(event, context)
  console.log('Recieved event', event)
  callback(null, { message: 'success' })
}
```

The event is empty.
Actually i expected the event will have the payload. like
```
{
      foo: 'bar'
}
```

## Additional Data
 Node Version:       7.6.0
 Serverless Version: 1.8.0
 Mac 10.12.3

**Comment by johncmckim** [comment]
Very good catch @yoyeung. This was a weird one. I've got a fix coming soon.
