### ISSUE TITLE
content-type negotiation failed

### ISSUE THREAD

**Issue by beau-midigator** [gertjvr/serverless-plugin-simulate#46]
# This is a Bug Report

## Description
I was attempting to POST a text/csv payload to a lambda and respond back with an application/json.   It appears that request templating is based on the accepts and not the incoming content-type which caused it to attempt to json.parse the body which would obviously fail.

For bug reports:
Described above.

For feature proposals:

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***:
0.0.10
* ***Serverless Docker Plugin Version you're using***:
* ***Operating System***:
centos-7.3
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by gertjvr** [comment]
Thanks for fixing this.
