### ISSUE TITLE
Incorrect velocityContext creation

### ISSUE THREAD

**Issue by beau-midigator** [gertjvr/serverless-plugin-simulate#54]
In lib/integration/lambda.js the context is created using:
const context = velocityContext.createFromResult(result)

However the function requires (req,result) arguments:
const createFromResult = (req, result)

This produced unexpected consequences when using custom responses.

# This is a (Bug Report / Feature Proposal)
Bug report

## Description
Incorrect usage / side effects for lambda integrations.

For bug reports:
Attempting to return a json parsed response within a response failed.

For feature proposals:

Similar or dependent issues:

## Additional Data
A simple test program to demonstrate the usage and subsequent failure.
`const velocityContext = require('./node_modules/serverless-plugin-simulate/lib/integration/velocity/context')
const velocityRenderer = require('./node_modules/serverless-plugin-simulate/lib/integration/velocity/renderer')
var a = {"pay" : "{\"count\": 2}", "statusCode" : 200}
var ctx = velocityContext.createFromResult(a, a)
console.log(velocityRenderer.render('$util.parseJson($input.json("pay"))', ctx))
var ctx = velocityContext.createFromResult(a)
console.log(velocityRenderer.render('$util.parseJson($input.json("pay"))', ctx))`

**Comment by beau-midigator** [comment]
My initial thought is it should be (result, result), right?

**Comment by johncmckim** [comment]
Thanks @beau-midigator  that's a good find. I'm fixing the issue now.
