### ISSUE TITLE
Change servicePath in serverless.yml

### ISSUE THREAD

**Issue by yoyeung** [gertjvr/serverless-plugin-simulate#56]
# This is a Feature Proposal

## Description

For feature proposals:
For the case i would like to use bable to compile my code to another dest like "dist" folder.
and library can get the compiled source code and execute it.

## Additional Data
like: babel services --out-dir dist/services

**Comment by yoyeung** [comment]
Please comment on my feature request and code.
This is my first open source pull request. = ]

**Comment by johncmckim** [comment]
@yoyeung thanks for contributing! @gertjvr and I have talked about this before. It's definitely a feature we need.

I've added some comments to your PR.

**Comment by yoyeung** [comment]
@johncmckim actually i am think about to integrate babel to this plugin.
is easy to add and watch babel logic.
in my design is look like use babel.transform to monitor src and dist folder.
Other config will use .babelrc provided by user.

Another step is monitor the serverless.yml.
When developer go to update js it will live compile
if developer change serverless.yml, it will live refresh.
Is it more close to the project goal? = ]

**Comment by gertjvr** [comment]
Hi @yoyeung 
Firstly thanks for adding the service path change.

I have been using serverless-webpack combined with service path change in offline previously to achieve this.

I dont think plugins should have a single purpose, pulling in the babel or webpack isn't a foxus of this plugin.

**Comment by yoyeung** [comment]
@gertjvr Good to hear the more clear vision for this plugin

**Comment by yoyeung** [comment]
@gertjvr after research  serverless-webpack plugin. But it live compile and watch the src.
Am I overlooked??

**Comment by johncmckim** [comment]
Thanks for contributing @yoyeung. I've merged your PR. Will release an update soon.

I'm not exactly sure I understand your question. But if webpack or babel is re-building your `dist` file on changes, it will automatically use the newly built code. Please let us know if that doesn't answer your question.

**Comment by yoyeung** [comment]
@johncmckim yup ur correct.

**Comment by ali-himindz** [comment]
Hi @johncmckim @gertjvr ,
I am not sure if I understand this correctly. But setting
simulate:
      services: docker-compose.yml
      dist: dist

My folder structure is /home/jenkins/git/src & /home/jenkins/git/dist
The dist folder contains src/index.js.

But when I do 
./node_modules/.bin/sls simulate  --stage dev apigateway -p 5000 --lambda-port 4000

I always uses the servicePath to be /home/jenkins/git.
The config value dist does not take affect.
Thanks in advance.
-Ali
